import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Platform } from 'react-native';

import { sendToBayMo } from '@/lib/baymo-chat';
import { supabase } from '@/lib/supabase';

/**
 * Agent-authored legal documents (table public.agent_documents). Drafts are
 * generated by the baymo-chat document engine (Claude Opus when available),
 * edited in-app, saved, and exported to a downloadable PDF via expo-print.
 */

export type DocStatus = 'draft' | 'final';

/** The standard PH real-estate document types offered in the app. */
export const DOC_TYPES = [
  'Authority to Sell',
  'Memorandum of Agreement',
  'Contract to Sell',
  'Letter of Intent',
  'Reservation Agreement',
] as const;

export type AgentDocument = {
  id: string;
  type: string;
  title: string;
  body: string;
  lead_id: string | null;
  status: DocStatus;
  updated_at: string;
};

const SELECT = 'id, type, title, body, lead_id, status, updated_at';

export async function fetchMyDocuments(): Promise<{ data: AgentDocument[]; error: string | null }> {
  const { data, error } = await supabase
    .from('agent_documents')
    .select(SELECT)
    .order('updated_at', { ascending: false })
    .limit(100);
  if (error) return { data: [], error: error.message };
  return { data: (data as AgentDocument[]) ?? [], error: null };
}

export async function fetchDocument(
  id: string,
): Promise<{ data: AgentDocument | null; error: string | null }> {
  const { data, error } = await supabase.from('agent_documents').select(SELECT).eq('id', id).maybeSingle();
  if (error) return { data: null, error: error.message };
  return { data: (data as AgentDocument) ?? null, error: null };
}

export async function createDocument(
  clientId: string,
  userId: string,
  input: { type: string; title: string; body: string; lead_id: string | null; status: DocStatus },
): Promise<{ id: string | null; error: string | null }> {
  const { data, error } = await supabase
    .from('agent_documents')
    .insert({ ...input, client_id: clientId, created_by: userId })
    .select('id')
    .single();
  if (error) return { id: null, error: error.message };
  return { id: (data as { id: string }).id, error: null };
}

export async function updateDocument(
  id: string,
  patch: Partial<{ title: string; body: string; status: DocStatus }>,
): Promise<{ error: string | null }> {
  const { error } = await supabase
    .from('agent_documents')
    .update({ ...patch, updated_at: new Date().toISOString() })
    .eq('id', id);
  return { error: error ? error.message : null };
}

export async function deleteDocument(id: string): Promise<{ error: string | null }> {
  const { error } = await supabase.from('agent_documents').delete().eq('id', id);
  return { error: error ? error.message : null };
}

/**
 * Ask BayMo to draft a document of `type`, using the agent's free-text context
 * (parties, property, price, dates). Returns PH-format text with [BRACKETED]
 * blanks for the agent to fill.
 */
export async function generateDocument(
  type: string,
  context: string,
): Promise<{ body: string | null; error: string | null }> {
  const prompt =
    `Draft a ${type} for a Philippine real estate transaction.` +
    (context.trim() ? `\n\nDetails provided by the agent:\n${context.trim()}` : '') +
    `\n\nUse [BRACKETED] placeholders for any detail not provided. Do not invent names, prices, or dates.`;
  const { reply, error } = await sendToBayMo([{ role: 'user', content: prompt }], 'document', type);
  if (error) return { body: null, error };
  return { body: reply ?? '', error: null };
}

// ── PDF export ─────────────────────────────────────────────────────────────

const esc = (s: string) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/** Build a simple, clean HTML page for the document. */
function documentHtml(doc: { type: string; title: string; body: string }): string {
  return `<!DOCTYPE html><html><head><meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<style>
  @page { margin: 48px; }
  body { font-family: Georgia, 'Times New Roman', serif; color: #1a1a1a; line-height: 1.6; font-size: 12pt; }
  .brand { color: #1F3C88; font-weight: 700; letter-spacing: 1px; font-family: Helvetica, Arial, sans-serif; font-size: 14pt; }
  .tag { color: #E67E22; font-size: 8pt; letter-spacing: 2px; font-family: Helvetica, Arial, sans-serif; }
  h1 { font-size: 15pt; text-align: center; text-transform: uppercase; margin: 24px 0 4px; }
  .type { text-align: center; color: #666; font-size: 9pt; margin-bottom: 24px; font-family: Helvetica, Arial, sans-serif; }
  .body { white-space: pre-wrap; }
  .disclaimer { margin-top: 40px; padding-top: 12px; border-top: 1px solid #ddd; color: #888; font-size: 8pt; font-family: Helvetica, Arial, sans-serif; }
</style></head>
<body>
  <div class="brand">BaMo</div>
  <div class="tag">REAL ESTATE MADE SIMPLE</div>
  <h1>${esc(doc.title || doc.type)}</h1>
  <div class="type">${esc(doc.type)}</div>
  <div class="body">${esc(doc.body)}</div>
  <div class="disclaimer">AI-generated draft prepared via BaMo. Review all details and consult a licensed professional before signing. BaMo is not a law firm and this is not legal advice.</div>
</body></html>`;
}

/**
 * Generate a PDF from the document and hand it to the OS share/save sheet so
 * the agent can download it (Files, Drive, Messenger, email, …).
 */
export async function exportDocumentPdf(doc: {
  type: string;
  title: string;
  body: string;
}): Promise<{ error: string | null }> {
  try {
    const html = documentHtml(doc);
    if (Platform.OS === 'web') {
      // On web, open the browser print dialog (user picks "Save as PDF").
      await Print.printAsync({ html });
      return { error: null };
    }
    const { uri } = await Print.printToFileAsync({ html });
    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: doc.title || doc.type, UTI: 'com.adobe.pdf' });
    }
    return { error: null };
  } catch (e) {
    return { error: String(e) };
  }
}
