import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Platform } from 'react-native';

import { sendToBayMo } from '@/lib/baymo-chat';
import { supabase } from '@/lib/supabase';

/**
 * Agent-authored legal documents (table public.agent_documents). Drafts are
 * generated by the baymo-chat document engine (Claude Opus when available),
 * edited in-app, saved, and exported to a downloadable PDF via expo-print.
 */

export type DocStatus = 'draft' | 'final';

/** The standard PH real-estate document types offered in the app. */
export const DOC_TYPES = [
  'Authority to Sell',
  'Memorandum of Agreement',
  'Contract to Sell',
  'Letter of Intent',
  'Reservation Agreement',
] as const;

export type DocType = (typeof DOC_TYPES)[number];

// ── Per-type intake forms ────────────────────────────────────────────────────
// Each document type asks for the details that actually matter for it, instead
// of one shared six-field form. Values feed the BayMo draft as labeled lines;
// anything left blank becomes a [BRACKETED] placeholder in the draft.

export type DocFieldKind = 'text' | 'amount' | 'percent' | 'multiline' | 'choice';

export type DocField = {
  key: string;
  label: string;
  placeholder?: string;
  kind?: DocFieldKind; // default 'text'
  choices?: readonly string[]; // for kind 'choice'
  autoCapitalize?: 'none' | 'words' | 'sentences';
};

export type DocTypeSchema = { fields: readonly DocField[]; promptHint: string };

const FINANCING = ['Cash', 'Pag-IBIG', 'Bank loan', 'In-house'] as const;

export const DOC_FIELD_SCHEMAS: Record<DocType, DocTypeSchema> = {
  'Authority to Sell': {
    promptHint:
      "This is a Philippine broker's Authority to Sell. State the authority period and whether it is exclusive or non-exclusive, the agent's commission, and that the owner warrants ownership and authority to sell.",
    fields: [
      { key: 'owner', label: 'Owner / Seller', placeholder: 'e.g. Kathy Talabis', autoCapitalize: 'words' },
      { key: 'property', label: 'Property', placeholder: 'e.g. Lot 5 Blk 3, Vermira Lipa, Batangas', autoCapitalize: 'words' },
      { key: 'title_no', label: 'Title no. (TCT/CCT)', placeholder: 'e.g. TCT-123456' },
      { key: 'price', label: 'Selling price', placeholder: '4,500,000', kind: 'amount' },
      { key: 'commission', label: 'Agent commission', placeholder: '2', kind: 'percent' },
      { key: 'authority_period', label: 'Authority period', placeholder: 'e.g. 6 months' },
      { key: 'exclusivity', label: 'Exclusivity', kind: 'choice', choices: ['Exclusive', 'Non-exclusive'] },
      { key: 'agent', label: 'Agent', placeholder: 'Your name', autoCapitalize: 'words' },
      { key: 'agent_prc', label: 'Agent PRC License No.', placeholder: 'e.g. 0012345' },
      { key: 'agent_company', label: 'Agent company / brokerage', placeholder: 'e.g. BaMo Realty', autoCapitalize: 'words' },
    ],
  },
  'Memorandum of Agreement': {
    promptHint:
      'This is a Philippine Memorandum of Agreement. Lay out the parties, the purpose/scope of the agreement, the key terms and obligations, and the effectivity date.',
    fields: [
      { key: 'party_a', label: 'First party', placeholder: 'Name / company', autoCapitalize: 'words' },
      { key: 'party_b', label: 'Second party', placeholder: 'Name / company', autoCapitalize: 'words' },
      { key: 'purpose', label: 'Purpose / scope', placeholder: 'What this agreement covers', kind: 'multiline', autoCapitalize: 'sentences' },
      { key: 'key_terms', label: 'Key terms', placeholder: 'Obligations, split, deliverables', kind: 'multiline', autoCapitalize: 'sentences' },
      { key: 'effectivity', label: 'Effectivity date', placeholder: 'e.g. July 15, 2026' },
    ],
  },
  'Contract to Sell': {
    promptHint:
      'This is a Philippine Contract to Sell. Include the total contract price, downpayment, the payment/amortization terms, financing method, and that title transfers upon full payment.',
    fields: [
      { key: 'seller', label: 'Seller', placeholder: 'e.g. Kathy Talabis', autoCapitalize: 'words' },
      { key: 'buyer', label: 'Buyer', placeholder: 'e.g. John Smith', autoCapitalize: 'words' },
      { key: 'property', label: 'Property', placeholder: 'e.g. Lot 5 Blk 3, Vermira Lipa', autoCapitalize: 'words' },
      { key: 'title_no', label: 'Title no. (TCT/CCT)', placeholder: 'e.g. TCT-123456' },
      { key: 'price', label: 'Total contract price', placeholder: '4,500,000', kind: 'amount' },
      { key: 'downpayment', label: 'Downpayment', placeholder: '500,000', kind: 'amount' },
      { key: 'payment_terms', label: 'Payment terms', placeholder: 'e.g. ₱50k/mo for 60 months', kind: 'multiline' },
      { key: 'financing', label: 'Financing', kind: 'choice', choices: FINANCING },
    ],
  },
  'Letter of Intent': {
    promptHint:
      'This is a Philippine Letter of Intent to purchase. State the offer price, earnest money, the offer validity period, and that the LOI is non-binding pending a formal contract.',
    fields: [
      { key: 'buyer', label: 'Buyer', placeholder: 'e.g. John Smith', autoCapitalize: 'words' },
      { key: 'seller', label: 'Seller / Developer', placeholder: 'e.g. Vermira Land Inc.', autoCapitalize: 'words' },
      { key: 'property', label: 'Property', placeholder: 'e.g. Lot 5 Blk 3, Vermira Lipa', autoCapitalize: 'words' },
      { key: 'offer_price', label: 'Offer price', placeholder: '4,300,000', kind: 'amount' },
      { key: 'earnest_money', label: 'Earnest money', placeholder: '100,000', kind: 'amount' },
      { key: 'validity', label: 'Offer validity', placeholder: 'e.g. 15 days' },
      { key: 'conditions', label: 'Conditions', placeholder: 'e.g. subject to bank approval', kind: 'multiline', autoCapitalize: 'sentences' },
    ],
  },
  'Reservation Agreement': {
    promptHint:
      'This is a Philippine Reservation Agreement for a developer unit/lot. State the reservation fee, that it is applied to the downpayment, the downpayment terms, financing method, and the reservation period.',
    fields: [
      { key: 'buyer', label: 'Buyer', placeholder: 'e.g. John Smith', autoCapitalize: 'words' },
      { key: 'developer', label: 'Developer / Seller', placeholder: 'e.g. Vermira Land Inc.', autoCapitalize: 'words' },
      { key: 'unit', label: 'Unit / Lot', placeholder: 'e.g. Lot 5 Blk 3, Vermira Lipa', autoCapitalize: 'words' },
      { key: 'list_price', label: 'Total list price', placeholder: '4,500,000', kind: 'amount' },
      { key: 'reservation_fee', label: 'Reservation fee', placeholder: '25,000', kind: 'amount' },
      { key: 'dp_terms', label: 'Downpayment terms', placeholder: 'e.g. 10% over 12 months', kind: 'multiline' },
      { key: 'financing', label: 'Financing', kind: 'choice', choices: FINANCING },
    ],
  },
};

/** Format one field's value for the AI context (₱ prefix / % suffix). */
function formatFieldValue(field: DocField, raw: string): string {
  const v = raw.trim();
  if (!v) return '';
  if (field.kind === 'amount') return `₱${v}`;
  if (field.kind === 'percent') return `${v}%`;
  return v;
}

/**
 * Turn the per-type field values (+ free-text "Other details") into the labeled
 * context block passed to BayMo. Only filled fields are included.
 */
export function composeDocContext(
  type: string,
  values: Record<string, string>,
  extra: string,
): string {
  const schema = DOC_FIELD_SCHEMAS[type as DocType];
  const parts: string[] = [];
  if (schema) {
    for (const field of schema.fields) {
      const formatted = formatFieldValue(field, values[field.key] ?? '');
      if (formatted) parts.push(`${field.label}: ${formatted}`);
    }
  }
  return [parts.join('\n'), extra.trim()].filter(Boolean).join('\n');
}

export type AgentDocument = {
  id: string;
  type: string;
  title: string;
  body: string;
  lead_id: string | null;
  status: DocStatus;
  updated_at: string;
};

const SELECT = 'id, type, title, body, lead_id, status, updated_at';

export async function fetchMyDocuments(): Promise<{ data: AgentDocument[]; error: string | null }> {
  const { data, error } = await supabase
    .from('agent_documents')
    .select(SELECT)
    .order('updated_at', { ascending: false })
    .limit(100);
  if (error) return { data: [], error: error.message };
  return { data: (data as AgentDocument[]) ?? [], error: null };
}

export async function fetchDocument(
  id: string,
): Promise<{ data: AgentDocument | null; error: string | null }> {
  const { data, error } = await supabase.from('agent_documents').select(SELECT).eq('id', id).maybeSingle();
  if (error) return { data: null, error: error.message };
  return { data: (data as AgentDocument) ?? null, error: null };
}

export async function createDocument(
  clientId: string,
  userId: string,
  input: { type: string; title: string; body: string; lead_id: string | null; status: DocStatus },
): Promise<{ id: string | null; error: string | null }> {
  const { data, error } = await supabase
    .from('agent_documents')
    .insert({ ...input, client_id: clientId, created_by: userId })
    .select('id')
    .single();
  if (error) return { id: null, error: error.message };
  return { id: (data as { id: string }).id, error: null };
}

export async function updateDocument(
  id: string,
  patch: Partial<{ title: string; body: string; status: DocStatus }>,
): Promise<{ error: string | null }> {
  const { error } = await supabase
    .from('agent_documents')
    .update({ ...patch, updated_at: new Date().toISOString() })
    .eq('id', id);
  return { error: error ? error.message : null };
}

export async function deleteDocument(id: string): Promise<{ error: string | null }> {
  const { error } = await supabase.from('agent_documents').delete().eq('id', id);
  return { error: error ? error.message : null };
}

/**
 * Ask BayMo to draft a document of `type`, using the agent's free-text context
 * (parties, property, price, dates). Returns PH-format text with [BRACKETED]
 * blanks for the agent to fill.
 */
export async function generateDocument(
  type: string,
  context: string,
): Promise<{ body: string | null; error: string | null }> {
  const hint = DOC_FIELD_SCHEMAS[type as DocType]?.promptHint ?? '';
  const prompt =
    `Draft a ${type} for a Philippine real estate transaction.` +
    (hint ? `\n\n${hint}` : '') +
    (context.trim() ? `\n\nDetails provided by the agent:\n${context.trim()}` : '') +
    `\n\nUse [BRACKETED] placeholders for any detail not provided. Do not invent names, prices, or dates.`;
  const { reply, error } = await sendToBayMo([{ role: 'user', content: prompt }], 'document', type);
  if (error) return { body: null, error };
  return { body: reply ?? '', error: null };
}

// ── PDF export ─────────────────────────────────────────────────────────────

const esc = (s: string) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/** Build a simple, clean HTML page for the document. */
function documentHtml(doc: { type: string; title: string; body: string }): string {
  return `<!DOCTYPE html><html><head><meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<style>
  @page { margin: 48px; }
  body { font-family: Georgia, 'Times New Roman', serif; color: #1a1a1a; line-height: 1.6; font-size: 12pt; }
  .brand { color: #1F3C88; font-weight: 700; letter-spacing: 1px; font-family: Helvetica, Arial, sans-serif; font-size: 14pt; }
  .tag { color: #E67E22; font-size: 8pt; letter-spacing: 2px; font-family: Helvetica, Arial, sans-serif; }
  h1 { font-size: 15pt; text-align: center; text-transform: uppercase; margin: 24px 0 4px; }
  .type { text-align: center; color: #666; font-size: 9pt; margin-bottom: 24px; font-family: Helvetica, Arial, sans-serif; }
  .body { white-space: pre-wrap; }
  .disclaimer { margin-top: 40px; padding-top: 12px; border-top: 1px solid #ddd; color: #888; font-size: 8pt; font-family: Helvetica, Arial, sans-serif; }
</style></head>
<body>
  <div class="brand">BaMo</div>
  <div class="tag">REAL ESTATE MADE SIMPLE</div>
  <h1>${esc(doc.title || doc.type)}</h1>
  <div class="type">${esc(doc.type)}</div>
  <div class="body">${esc(doc.body)}</div>
  <div class="disclaimer">AI-generated draft prepared via BaMo. Review all details and consult a licensed professional before signing. BaMo is not a law firm and this is not legal advice.</div>
</body></html>`;
}

/**
 * Generate a PDF from the document and hand it to the OS share/save sheet so
 * the agent can download it (Files, Drive, Messenger, email, …).
 */
export async function exportDocumentPdf(doc: {
  type: string;
  title: string;
  body: string;
}): Promise<{ error: string | null }> {
  try {
    const html = documentHtml(doc);
    if (Platform.OS === 'web') {
      // On web, open the browser print dialog (user picks "Save as PDF").
      await Print.printAsync({ html });
      return { error: null };
    }
    const { uri } = await Print.printToFileAsync({ html });
    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: doc.title || doc.type, UTI: 'com.adobe.pdf' });
    }
    return { error: null };
  } catch (e) {
    return { error: String(e) };
  }
}
